# Buildpacks to include in builder
[[buildpacks]]
id = "io.caicloud.nodejs"
version = "0.0.1"
uri = "../buildpacks/NodeJs"

# Order used for detection
[[order]]
[[order.group]]
id = "io.caicloud.nodejs"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.caicloud.stacks.bionic"
run-image = "caicloud-run:bionic"
build-image = "caicloud-build:bionic"
